(function(g){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,b=r?r("CustomerReviewsVotingAssets"):p;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,p,r){g.when("A","vote-model","vote-view","a-modal").register("vote-controller",function(b,a,d,e){function f(a,b){c(a,b);d.showElementByCssSelector(a,b.inFlight)}function c(a,b){d.hideElementByCssSelector(a,b.hideVoteComponents);b.hideAbuseComponents&&d.hideElementByCssSelector(a,b.hideAbuseComponents)}
function h(h,g){g.isReportAbuse&&(h=b.$("#mobile-abuse-"+g.voteInstanceId),e.get(h).hide());f(h,g.cssSelectors);a.submitVote(g.ajaxUrl,g.voteValue,g.voteInstanceId,g.csrfT,function(a){if(!0===a){a=h;var b=g.cssSelectors;c(a,b);d.showElementByCssSelector(a,b.onSuccess)}else a=h,b=g.cssSelectors,c(a,b),d.showElementByCssSelector(a,b.onError)},function(){var a=h,b=g.cssSelectors;c(a,b);d.showElementByCssSelector(a,b.onError)})}b.declarative("reviews:vote-action","click",function(a){h(a.$target,a.data);
a.$event.preventDefault()});return{submitVote:h}});g.when("A","cr-ajax-model").register("vote-model",function(b,a){return{submitVote:function(b,e,f,c,h,g){a.post(b,{params:{voteInstanceId:f,voteValue:e,csrfT:c},attribution:"submitVote",success:h,error:g})}}});g.when("A").register("vote-view",function(b){function a(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(b){a(b,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(b){a(b,
".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(b){a(b,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(b){a(b,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(b){a(b,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(b){a(b,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(b,e){a(b,e).addClass("aok-hidden")},showElementByCssSelector:function(b,e){a(b,e).removeClass("aok-hidden")}}})});
/* ******** */
(function(g){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,b=r?r("CustomerReviewsGalleryAssets"):p;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,p,r){g.when("A","load").register("review-image-asset-loader",function(b){var a=!1;b.ajax("/gp/customer-reviews/aj/private/reviewsGallery/get-image-gallery-assets",{method:"post",success:function(b){g.load.css(b.reviewsLightboxCSS);g.load.js(b.reviewsLightboxJS);a=!0;g.register("review-image-assets-loaded",
{})},error:function(){var a;a="/gp/customer-reviews/aj/metrics/log-values?noCache="+(new Date).getTime();a+="&SimpleStack:ReviewImageAssetLoaderFailure=1";p.Image&&((new Image).src=a)}});return{isLoaded:function(){return a}}});g.when("A","jQuery","cr-log-utils","review-image-assets-loaded").register("review-image-binder",function(b,a,d){function e(b,c,e,k,q){if(!(b&&c&&e instanceof a&&k instanceof a&&q instanceof a))return d.logError("Invalid parameters for imageBinder.initializeForAsin with ASIN: "+
b+", galleryName: "+c+", $popoverTrigger: "+e+", $thumbnails: "+k+", $galleryLink: "+q,"FATAL"),!1;(new ReviewsLightbox(c,"DESKTOP")).initializeForAsin(b);var l="reviewsLightbox-ready-"+c;k.click(function(){var b=k.index(this);e.click();g.when(l).execute(function(){a("#"+c).trigger("jumpToImageAtIndex",b)})});q.click(function(){e.click();g.when(l).execute(function(){a("#"+c).trigger("hideImmersiveView")})});return!0}g.when("reviewsLightbox-js").execute(function(){var b=a("#reviews-image-gallery-container"),
d=b.attr("data-asin");0<b.length&&d&&e(d,"reviews-image-gallery",b.find(".a-popover-trigger"),b.find(".review-image-tile"),b.find("#reviews-image-gallery-link"))});return{bindReview:function(b,d,e){var k=new ReviewGallery(e,"DESKTOP");k.initializeForReview(b);var q=a("#"+d);q.find(".review-image-tile").each(function(b){a(this).click(function(){q.find(".a-popover-trigger").click();g.when("reviewsLightbox-ready-"+e).execute(function(){k.render();k.showImageAtIndex(b)})})})},initializeForAsin:e}});
g.when("A","jQuery","cr-video-model","cr-video-view","reviews-constants").register("cr-video-controller",function(b,a,d,e,f){function c(){b.each(a(".review-views .review"),function(a,b){if(a&&a.id){var c=d.getEmbedInfo(a.id);c&&e.embedVideo(c)}})}b.on(f.events.RELOAD_COMPLETE,function(){c()});c();return{initAll:c}});g.when("jQuery").register("cr-video-model",function(b){return{getEmbedInfo:function(a){var d="video-block-"+a,e=b("#"+a+" .video-url").val(),f=b("#"+a+" .video-slate-img-url").val(),
c=b("#cr-video-swf-url").val();return a&&e&&c?{videoDomId:d,videoUrl:e,videoSlateImgUrl:f,videoSwfUrl:c}:!1}}});g.when("jQuery","afterLoad").register("cr-video-view",function(b){g.now("Airy").execute(function(a){var d=b("#cr-airy-js-source-url").val(),e=b("#cr-airy-css-source-url").val();a||"string"!==typeof d||"string"!==typeof e||(g.load.js(d),g.load.css(e))});return{embedVideo:function(a){g.when("Airy").execute(function(b){b.embed({parentId:a.videoDomId,streamingUrls:[a.videoUrl],
slateImages:{preloadSlate:a.videoSlateImgUrl},swfUrl:a.videoSwfUrl})})}}})});
/* ******** */
