(function(g){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,b=r?r("CustomerReviewsCommonAssets"):p;b.guardFatal?b.guardFatal(g)(b,window):b.execute(function(){g(b,window)})})(function(g,p,r){g.when("A","cr-log-utils").register("cr-ajax-model",function(b,a){function d(a){h[a]&&(h[a].abort(),delete h[a])}function e(k,q,l,g,t,n,r){var A;A=n?n:c=c++;n=A;t=t?t:q.error||function(){};g=g?g:0;l=l?l:3;var E=q.finallyCallback||function(){};r||(r="reviewsAjax"+f++,p.uet&&p.uet("tc",
r));q.params.scope=r;q.contentType="application/x-www-form-urlencoded;charset=UTF-8";var z=q.success||function(){};q.success=function(a){delete h[n];"function"===typeof z&&z(a);"function"===typeof E&&E(a)};q.error=function(b){d(n);g++;g<l?(a.logError("AJAX Post to "+k+" failed, Attempt: "+g+" out of "+l,"WARN"),e(k,q,l,g,t,n,r)):(a.logError("AJAX Post to "+k+" from "+p.location.href+" failed, exhausted "+l+" attempts","FATAL"),"function"===typeof t&&t(b),"function"===typeof E&&E(b))};h[n]=b.post(k,
q);return n}var f=0,c=1,h={};return{abort:d,post:e}});g.when("A","jQuery").register("cr-A",function(b,a){var d={top:-100,left:-100};b.inView=function(b){b=b||a();if("function"===typeof b.offset){var f=(b.offset()||d).top-a(p).scrollTop();b=0<=f;f=f<a(p).height();return b&&f}return!1};b.onScreenAndVisible=function(){b.onScreen.apply(this,arguments)};return b});g.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",
CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",
FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",
CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",FEEDBACK_CLICK:"reviews:skyfall-feedback-click",CLIQUE_CLICK:"reviews:skyfall-clique-click",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},filterOptions:{SORT_KEY:"sortBy",
HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews"},
keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});g.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,a,d){function e(e){var c={};e&&e.data&&(c=e.data);var h=a.defaultIfBlank(c.url,e.$target.find("a").andSelf().filter("a").attr("href")),k=a.defaultIfBlank(c.title,"CustomerReviews"),k=""+k,g="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(b,d){var e=a.defaultIfBlank(c[d],b);
g+=d+"="+e+","});var g=g.slice(0,-1),l=null;try{(l=p.open(h,k,g))?l.focus():d.logError("Unable to move focus to popup window with data: "+a.stringify(c),"ERROR"),e.$event.preventDefault()}catch(r){d.logError("Unable to open window with parameters: "+a.stringify(c),"FATAL",r)}return l}b.declarative("cr-popup",["click"],d.jsGuard(e));return{popup:e}});g.when("A","jQuery","reviews-constants").register("cr-generic-declarative-actions",function(b,a,d){function e(b){b&&b.data&&b.data.selector&&
b.data.cssClass&&b.$event&&"function"===typeof b.$event.preventDefault&&(a(b.data.selector).toggleClass(b.data.cssClass),b.$event.preventDefault())}b.declarative(d.events.TOGGLE_CLASS_CLICK,"click",e);return{toggleCssClass:e}});g.when("A","ready").register("cr-global-model",function(b){var a=b.state("reviews-page-state");a||(a=b.$("#cr-state-object").data("state"));var d=null;a&&(d=a.customerId);return{generateUrl:function(a,b){var d=a;d&&"/"!==d.charAt(d.length-1)&&(d+="/");d&&b&&(d=
d+"ref="+b);return d},isSignedIn:function(){return d?!0:!1}}});g.when("A","a-expander","jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,a,d,e,f){function c(a){var b="";if(a&&a.closest!==r){var d=a.closest("*["+u.REFTAG+"]");d&&(b=d.attr(u.REFTAG))}f.isBlank(b)&&a&&a.closest!==r&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return f.defaultIfBlank(b,"cm_cr_unknown")}function h(a){return a&&"function"===typeof a.is?a.is("*["+u.getReviews.CHECKED+"]")&&
a.is("*["+u.getReviews.UNCHECKED+"]"):!1}function k(a){return a&&a.has!==r&&a.is!==r?0<a.find(":checked").length||a.is(":checked"):!1}function g(a,b){return a&&a.attr!==r&&b?f.parseJSON(a.attr(b))||{}:{}}function l(a){return a!==r}var u=e.data;b.on("a:expander:review_text_read_more:toggle:collapse",function(a){l(a)&&l(a.expander)&&l(a.expander.$expander)&&1===a.expander.$expander.length&&l(a.expander.$expander[0].closest(".review"))&&l(a.expander.$expander[0].closest(".review").offsetTop)&&(a=a.expander.$expander[0].closest(".review").offsetTop,
p.scroll(0,a))});b.on("a:pageUpdate",function(){l(a)&&a.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var d=b.reduce(u.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),c;d&&a&&a.closest!==r&&(c=a.closest(d));return h(c)?k(c)?g(c,u.getReviews.CHECKED):g(c,u.getReviews.UNCHECKED):g(c,u.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&(b=a.$target);a&&a.id&&(b=d("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=c(b);
"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:c}});g.when("A").register("cr-log-utils",function(b){function a(a,b,d){p.ueLogError&&("string"!==typeof b&&(b="FATAL"),d?p.ueLogError(d,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):p.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function d(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:a,jsGuard:function(b){if("function"===
typeof b)return function(){try{return b.apply(this,arguments)}catch(d){a("Uncaught Error in function","FATAL",d)}};a("Unable to wrap non-function","ERROR");return b},incrementCount:function(a,b){if(p.ue){var c=d(a,b),h=p.ue.count(c)||0;p.ue.count(c,h+1)}},logCount:function(a,b,c){p.ue&&(a=d(a,c),p.ue.count(a,b))}}});g.register("cr-mash-utils",function(){var b=!1;g.when("mash").execute(function(){b=!0});return{isMash:function(){return b}}});g.when("A","cr-log-utils").register("cr-number-utils",
function(b,a){return{convertToInteger:function(b,e){if(b===parseInt(b,10))return b;if(null!==b&&b!==r&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(e!==r)return e;a.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0}}});g.when("A","jQuery").register("cr-streaming-utils",function(b,a){return{appendFadeIn:function(d){if(null!==d&&2<d.length&&null!==d[1]&&null!==d[2]){var e=d[1];d=a(d[2]).hide();a(e).append(d);b.fadeIn(d,500,"ease-in-out",function(){})}}}});
g.when("A","cr-log-utils").register("cr-string-utils",function(b,a){function d(a){return null===a||a===r?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return d(a)?b:a},isBlank:d,parseJSON:function(d){try{return b.parseJSON(d)}catch(f){a.logError("Unable to parse JSON object","ERROR",f)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},stringify:function(a){return p.JSON&&p.JSON.stringify?p.JSON.stringify(a):a}}});
g.when("A","cr-string-utils","3p-urijs").register("cr-uri-utils",function(b,a,d){function e(){return d(p.location.href)}function f(){return e().query()}return{getCurrentUri:e,getCurrentQueryString:f,getCurrentQueryParameters:function(){return d.parseQuery(f())},isAmazonDomain:function(b){if("string"===typeof b||b instanceof String)b=d(b);var e=a.startsWith(b.domain(),"amazon");!1===e&&(b=b.hostname(),b=b.substring(b.indexOf(".")+1),e=a.startsWith(b,"amazon"));return e},setQueryParameters:function(c,
e){if("string"===typeof c||c instanceof String)c=d(c);b.each(e,function(b,d){a.isBlank(b)?c.removeSearch(d):c=c.setSearch(d,b)});return c},setReftag:function(b,e){if("string"===typeof b||b instanceof String)b=d(b);for(var f=b.segment(),g=!1,l=f.length-1;0<=l;l--)if(a.startsWith(f[l],"ref=")){g=!0;f[l]="ref="+e;break}g||f.push("ref="+e);b.segment(f);return b}}});g.when("cr-A","jQuery","cr-log-utils","cr-string-utils","afterReady").register("cr-weblab-utils",function(b,a,d,e){function f(e,
f,h,n){k[f]||(d.logCount(h,0,n),e=c(a(e),f,h,n)(),g[f]=(g[f]||[]).concat(e),b.on.scroll(e))}function c(a,d,c,e){return function A(){b.inView(a)&&(h(d,c,e),b.each(g[d]||[],function(a){b.off("scroll",a)}));return A}}function h(a,c,e){k[a]||(k[a]=!0,b.post("/ss/customer-reviews/ajax/weblab-trigger",{params:{weblabId:a}}),d.logCount(c,1,e))}var k={},g={};b.each(a("*[data-cr-weblab-trigger-on-scroll]"),function(b,d){var c=a(b),h=c.attr("data-cr-weblab-trigger-on-scroll"),h=e.parseJSON(h);if(null!==h){var k=
"cr-weblab-trigger-on-scroll-"+d;c.addClass(k);f("."+k,h.weblabId,h.metricName,h.prefix)}});return{triggerOnScrollIntoView:f,triggerWeblab:h}});g.when("A").register("histogram-trigger",function(b){function a(){b.onScreen(b.$("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(a);return{triggerHistogram:a}})});